mode: mixture
datasets:
  - name: pointodyssey
    root: /mnt/d/data/ZBF_Data/d4rt/PointOdyssey
    weight: 0.4
  - name: scannet
    root: /mnt/d/data/ZBF_Data/d4rt/ScanNet
    weight: 0.3
  - name: co3dv2
    root: /mnt/d/data/ZBF_Data/d4rt/Co3Dv2
    weight: 0.3

clip_len: 48
img_size: 256
num_queries: 2048
use_augs: true
boundary_ratio: 0.3
t_tgt_eq_t_cam_ratio: 0.4
seed: 42
